# Generated by Django 3.1.1 on 2020-10-25 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_text', models.CharField(max_length=200)),
                ('character_name', models.CharField(max_length=50)),
                ('book_name', models.CharField(max_length=200)),
            ],
        ),
    ]
