# Generated by Django 3.1.1 on 2020-11-01 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
